name: CI Project3

on:
  push:
    branches:
      - main

jobs:
  hello-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test simple
        run: echo "CI fonctionne pour Project3"

